server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        show_sql: true
        format_sql: true
  datasource:
    username: "admin"
    password: "gbT^%4"
    url: "jdbc:postgresql://localhost:5402/shop"
    driver-class-name: org.postgresql.Driver
