server:
  port: 3003
spring:
  main:
    web-application-type: servlet
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: "admin"
    password: "fgDE%464"
    url: "jdbc:postgresql://localhost:5402/devs"
    driver-class-name: org.postgresql.Driver